In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import data

In [3]:
data_repo = "/home/julien/src/DSC_HOME_SERVICE/data/"
import_params = {'sep': '|', 'encoding': 'latin-1'}

In [4]:
date_cols = ['CRE_DATE', 'UPD_DATE', 'DATE_RESILIATION', 'DATE_DEBUT', 'DATE_FIN']
contract_history = pd.read_csv(data_repo + 'contract_history.csv', dtype={'NUM_CAMPAGNE': object}, parse_dates=date_cols, **import_params)

In [84]:
contract_history.dtypes

STS_CODE                         object
CONTRACT_NUMBER                   int64
CONTRACT_MODIFICATEUR            object
CRE_DATE                 datetime64[ns]
UPD_DATE                 datetime64[ns]
DATE_RESILIATION         datetime64[ns]
DATE_DEBUT               datetime64[ns]
DATE_FIN                 datetime64[ns]
INSTANCE_ID                       int64
FORMULE                          object
OPTION                           object
CONTRAT_TARIF                     int64
PRIX_FACTURE                      int64
CONDITION_REGLEMENT              object
MOTIF_RESILIATION                object
RENOUVELLEMENT_AGENCE            object
PRIX_FORMULE                      int64
PRIX_OPTION                       int64
NUM_CAMPAGNE                     object
dtype: object

In [49]:
# normalization to put everything in float and convert "N" to nan
contract_history['NUM_CAMPAGNE'] = contract_history['NUM_CAMPAGNE'].map(lambda x: float(x) if x not in ['N', ''] else np.nan)

In [38]:
equipment = pd.read_csv(data_repo + 'equipment.csv', dtype={'CODE_POSTAL': object}, **import_params)

In [40]:
equipment.dtypes

INSTANCE_ID                 int64
LOCATION_ID                 int64
ORGANISATION_ID             int64
PARTY_ID_OCC                int64
TYPE_OCC                   object
INSTALL_DATE               object
RACHAT_CODE                object
RACHAT_LIB                 object
RACHAT_DATE                object
NATURE_CODE                object
MARQUE_CODE               float64
MARQUE_LIB                 object
MODELE_CODE                object
MODELE_LIB                 object
USAGE_LOCAL                object
LOCALISATION_ORGANISME     object
COMPLEMENT_RUE             object
CODE_POSTAL                object
ESCALIER                   object
ETAGE                      object
NUMERO                     object
RUE                        object
PAYS                       object
TYPE_VOIE                  object
VILLE                      object
POINTS_FIDEL              float64
STOP_PHONING               object
CODE_GEN_EQUIPEMENT        object
CODE_FONCTION              object
CODE_ENERGIE              float64
CODE_INSTALLATION          object
CODE_SPECIFICATION         object
CODE_EAU_CHAUDE            object
dtype: object

In [44]:
code_eau_chaude = pd.read_csv(data_repo + 'nature_code_eau_chaude.csv', sep='|')
code_energie = pd.read_csv(data_repo + 'nature_code_energie.csv', sep='|')
code_fonction = pd.read_csv(data_repo + 'nature_code_fonction.csv', sep='|')
code_installation = pd.read_csv(data_repo + 'nature_code_installation.csv', sep='|')
code_specification = pd.read_csv(data_repo + 'nature_code_specification.csv', sep='|')

In [5]:
date_cols = ['CRE_DATE_GZL', 'SCHEDULED_START_DATE', 'SCHEDULED_END_DATE']
date_cols_history = ['ACTUAL_START_DATE', 'ACTUAL_END_DATE']

intervention_test = pd.read_csv(data_repo + 'intervention_test.csv', sep='|', encoding='latin-1', parse_dates=date_cols)
intervention_history = pd.read_csv(data_repo + 'intervention_history.csv', sep='|', encoding='latin-1', parse_dates=date_cols+date_cols_history)
intervention_train = pd.read_csv(data_repo + 'intervention_train.csv', sep='|', encoding='latin-1', parse_dates=date_cols)

In [134]:
intervention_test.dtypes

INSTANCE_ID                      int64
INCIDENT_NUMBER                  int64
INCIDENT_TYPE_ID                 int64
INCIDENT_TYPE_NAME              object
TYPE_BI                         object
NB_PASSAGE                     float64
MILLESIME                      float64
PROBLEM_CODE                    object
PROBLEM_DESC                   float64
AUTEUR_INCIDENT                  int64
ORIGINE_INCIDENT                object
COMMENTAIRE_BI                  object
SS_TR_FLAG                      object
TYPE_UT                         object
GRAVITE                         object
RESOURCE_ID                    float64
SCHEDULED_START_DATE    datetime64[ns]
SCHEDULED_END_DATE      datetime64[ns]
CRE_DATE_GZL            datetime64[ns]
dtype: object

In [52]:
intervention_train.dtypes

INSTANCE_ID               int64
INCIDENT_NUMBER           int64
INCIDENT_TYPE_ID          int64
INCIDENT_TYPE_NAME       object
TYPE_BI                  object
NB_PASSAGE              float64
MILLESIME               float64
PROBLEM_CODE             object
PROBLEM_DESC            float64
AUTEUR_INCIDENT           int64
ORIGINE_INCIDENT         object
COMMENTAIRE_BI           object
SS_TR_FLAG               object
TYPE_UT                  object
GRAVITE                  object
RESOURCE_ID             float64
SCHEDULED_START_DATE     object
SCHEDULED_END_DATE       object
CRE_DATE_GZL             object
target                    int64
dtype: object

In [14]:
intervention_history.dtypes

INSTANCE_ID                        int64
INCIDENT_NUMBER                    int64
DATE_SAISIE_RETOUR                object
INCIDENT_TYPE_ID                   int64
INCIDENT_TYPE_NAME                object
INCIDENT_STATUS_ID                 int64
INCIDENT_STATUS_NAME              object
INCIDENT_STATUS_CODE              object
INCIDENT_CLOSED_FLAG              object
TYPE_BI                           object
NB_PASSAGE                       float64
MILLESIME                        float64
PROBLEM_CODE                      object
PROBLEM_DESC                     float64
MOTIF_A_REVOIR                   float64
AUTEUR_INCIDENT                    int64
ORIGINE_INCIDENT                  object
COMMENTAIRE_BI                    object
SS_TR_FLAG                        object
TYPE_UT                           object
GRAVITE                           object
COMMENTAIRE_FIN_INTERV            object
MOTIF_ANNULATION_CODE             object
MOTIF_ANNULATION_DESC             object
RESOURCE_ID                      float64
SCHEDULED_START_DATE      datetime64[ns]
SCHEDULED_END_DATE        datetime64[ns]
ACTUAL_START_DATE         datetime64[ns]
ACTUAL_END_DATE           datetime64[ns]
CRE_DATE_GZL              datetime64[ns]
dtype: object

In [62]:
organisation = pd.read_csv(data_repo + 'organisation.csv', **import_params)

In [63]:
organisation.dtypes

L1_ORGANISATION_ID      int64
L1_NAME                object
L2_ORGANISATION_ID      int64
L2_NAME                object
ADRESSE                object
L2_ORGA_CODE_POSTAL     int64
L2_ORGA_VILLE          object
CIA                     int64
ORGANISATION_CODE      object
dtype: object

In [ ]:
# what's the point of separating train and history ?

In [62]:
print(intervention_history.shape)
print(intervention_train.shape)
print(intervention_test.shape)

(5171308, 30)
(1048030, 20)
(226770, 19)

In [63]:
intervention_test['CRE_DATE_GZL'].min(), intervention_test['CRE_DATE_GZL'].max()

('2014-01-06', '2017-10-21')

In [60]:
intervention_train['CRE_DATE_GZL'].min(), intervention_train['CRE_DATE_GZL'].max()

('2014-01-06', '2017-10-21')

In [61]:
intervention_history['CRE_DATE_GZL'].min(), intervention_history['CRE_DATE_GZL'].max()

('2014-01-02', '2018-04-26')

## Are the observation in train and test also in history ? : 
train = yes
<br>
test = no --> impossible to build features based on history
<br>
note: 
* neither of tuples ('INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER') nor ('INSTANCE_ID', 'CRE_DATE_GZL') in test set are present in history
* 'INSTANCE_ID' in test set are presents in history

** to create features based on history, we have to join test and history to gather the maximum of informations (if we can build intereting features based on that join **

In [34]:
# common observations in history and train ?
intervention_train.reset_index(inplace=True)
intervention_train.set_index(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER'], inplace=True)

In [35]:
intervention_test.reset_index(inplace=True)
intervention_test.set_index(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER'], inplace=True)

In [36]:
intervention_history.reset_index(inplace=True)
intervention_history.set_index(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER'], inplace=True)

In [37]:
intervention_history.columns

Index(['index', 'DATE_SAISIE_RETOUR', 'INCIDENT_TYPE_ID', 'INCIDENT_TYPE_NAME',
       'INCIDENT_STATUS_ID', 'INCIDENT_STATUS_NAME', 'INCIDENT_STATUS_CODE',
       'INCIDENT_CLOSED_FLAG', 'TYPE_BI', 'NB_PASSAGE', 'MILLESIME',
       'PROBLEM_CODE', 'PROBLEM_DESC', 'MOTIF_A_REVOIR', 'AUTEUR_INCIDENT',
       'ORIGINE_INCIDENT', 'COMMENTAIRE_BI', 'SS_TR_FLAG', 'TYPE_UT',
       'GRAVITE', 'COMMENTAIRE_FIN_INTERV', 'MOTIF_ANNULATION_CODE',
       'MOTIF_ANNULATION_DESC', 'RESOURCE_ID', 'SCHEDULED_START_DATE',
       'SCHEDULED_END_DATE', 'ACTUAL_START_DATE', 'ACTUAL_END_DATE'],
      dtype='object')

In [38]:
intervention_train.sort_index(inplace=True)
intervention_test.sort_index(inplace=True)
intervention_history.sort_index(inplace=True)
intervention_train.head(30)

                                            index  INCIDENT_TYPE_ID  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876          538879             10005
            2017-01-19   81119814          381986             10005
            2017-02-01   81505320          254996             10005
10015       2015-11-12   68333220          776854             10005
            2016-07-25   75830488          814224             10005
10017       2016-12-23   80266556          164690             10005
10021       2017-03-20   83022676          480769             10005
            2017-03-30   83345306           10698             10005
10023       2016-02-03   70993496          955900             10005
            2016-02-08   71169146          326080             10005
            2016-04-08   72963744          866167             10003
            2016-05-09   73770436          580684             10003
            2016-07-06   75416978          755863             10003
            2016-10-12   77868812          193216             10003
10025       2014-10-27   57045898          276016             10003
10027       2015-09-08   66168882          959955             10005
10033       2016-03-02   71866090          109151             10003
            2016-03-08   72021978          848888             10003
            2016-06-07   74619430          878264             10005
10034       2016-10-18   78097774          221127             10005
            2016-11-21   79087650           58106             10005
            2017-10-19   88816958          733632             10005
10037       2016-02-02   70979254          696499             10005
10040       2016-07-25   75823102          433364             10005
            2017-06-14   85398850          204702             10005
10042       2016-09-15   77034534          848373             10005
            2016-10-11   77797196         1039889             10005
10052       2015-06-24   64360738           97083             10005
10056       2016-09-13   76938778           40521             10005
            2016-10-12   77849866         1032631             10003

                                         INCIDENT_TYPE_NAME    TYPE_BI  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876                 Entretien  Entretien
            2017-01-19   81119814                 Entretien  Entretien
            2017-02-01   81505320                 Entretien  Entretien
10015       2015-11-12   68333220                 Entretien  Entretien
            2016-07-25   75830488                 Entretien  Entretien
10017       2016-12-23   80266556                 Entretien  Entretien
10021       2017-03-20   83022676                 Entretien  Entretien
            2017-03-30   83345306                 Entretien  Entretien
10023       2016-02-03   70993496                 Entretien  Entretien
            2016-02-08   71169146                 Entretien  Entretien
            2016-04-08   72963744                 Dépannage  Dépannage
            2016-05-09   73770436                 Dépannage  Dépannage
            2016-07-06   75416978                 Dépannage  Dépannage
            2016-10-12   77868812                 Dépannage  Dépannage
10025       2014-10-27   57045898                 Dépannage  Dépannage
10027       2015-09-08   66168882                 Entretien  Entretien
10033       2016-03-02   71866090                 Dépannage  Dépannage
            2016-03-08   72021978                 Dépannage  Dépannage
            2016-06-07   74619430                 Entretien  Entretien
10034       2016-10-18   78097774                 Entretien  Entretien
            2016-11-21   79087650                 Entretien  Entretien
            2017-10-19   88816958                 Entretien  Entretien
10037       2016-02-02   70979254                 Entretien  Entretien
10040       2016-07-25   75823102                 Entretien  Entretien
            2017-06-14   85398850                 Entretien  Entretien
10042       2016-09-15   77034534                 Entretien  Entretien
            2016-10-11   77797196                 Entretien  Entretien
10052       2015-06-24   64360738                 Entretien  Entretien
10056       2016-09-13   76938778                 Entretien  Entretien
            2016-10-12   77849866                 Dépannage  Dépannage

                                          NB_PASSAGE  MILLESIME PROBLEM_CODE  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876                1.0     2017.0          NaN
            2017-01-19   81119814                1.0     2017.0          NaN
            2017-02-01   81505320                1.0     2017.0          NaN
10015       2015-11-12   68333220                1.0     2015.0          NaN
            2016-07-25   75830488                1.0     2016.0          NaN
10017       2016-12-23   80266556                1.0     2017.0          NaN
10021       2017-03-20   83022676                1.0     2017.0          NaN
            2017-03-30   83345306                2.0     2017.0          NaN
10023       2016-02-03   70993496                1.0     2016.0          NaN
            2016-02-08   71169146                1.0     2016.0          NaN
            2016-04-08   72963744                1.0        NaN          NaN
            2016-05-09   73770436                1.0        NaN          NaN
            2016-07-06   75416978                1.0        NaN          NaN
            2016-10-12   77868812                NaN        NaN          NaN
10025       2014-10-27   57045898                1.0        NaN          NaN
10027       2015-09-08   66168882                1.0     2015.0          NaN
10033       2016-03-02   71866090                1.0        NaN          NaN
            2016-03-08   72021978                1.0        NaN          NaN
            2016-06-07   74619430                1.0        NaN          NaN
10034       2016-10-18   78097774                1.0     2016.0          NaN
            2016-11-21   79087650                1.0     2016.0          NaN
            2017-10-19   88816958                1.0     2017.0          NaN
10037       2016-02-02   70979254                1.0     2015.0          NaN
10040       2016-07-25   75823102                1.0     2016.0          NaN
            2017-06-14   85398850                1.0     2017.0          NaN
10042       2016-09-15   77034534                1.0     2016.0          NaN
            2016-10-11   77797196                1.0     2016.0          NaN
10052       2015-06-24   64360738                1.0     2015.0          NaN
10056       2016-09-13   76938778                1.0     2016.0          NaN
            2016-10-12   77849866                1.0        NaN          NaN

                                          PROBLEM_DESC  AUTEUR_INCIDENT  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876                  NaN             1513
            2017-01-19   81119814                  NaN            33678
            2017-02-01   81505320                  NaN             1488
10015       2015-11-12   68333220                  NaN            24270
            2016-07-25   75830488                  NaN             1513
10017       2016-12-23   80266556                  NaN            24270
10021       2017-03-20   83022676                  NaN             1486
            2017-03-30   83345306                  NaN             1486
10023       2016-02-03   70993496                  NaN             1513
            2016-02-08   71169146                  NaN             1483
            2016-04-08   72963744                  NaN             1483
            2016-05-09   73770436                  NaN             1614
            2016-07-06   75416978                  NaN             1614
            2016-10-12   77868812                  NaN             1483
10025       2014-10-27   57045898                  NaN             1492
10027       2015-09-08   66168882                  NaN             1513
10033       2016-03-02   71866090                  NaN             1614
            2016-03-08   72021978                  NaN             1614
            2016-06-07   74619430                  NaN             1489
10034       2016-10-18   78097774                  NaN             1513
            2016-11-21   79087650                  NaN            37990
            2017-10-19   88816958                  NaN            21231
10037       2016-02-02   70979254                  NaN             1513
10040       2016-07-25   75823102                  NaN             1513
            2017-06-14   85398850                  NaN            21231
10042       2016-09-15   77034534                  NaN             1513
            2016-10-11   77797196                  NaN             1486
10052       2015-06-24   64360738                  NaN             1513
10056       2016-09-13   76938778                  NaN             1513
            2016-10-12   77849866                  NaN             1488

                                         ORIGINE_INCIDENT  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876             Automatique
            2017-01-19   81119814               Téléphone
            2017-02-01   81505320               Téléphone
10015       2015-11-12   68333220             Automatique
            2016-07-25   75830488             Automatique
10017       2016-12-23   80266556             Automatique
10021       2017-03-20   83022676               Téléphone
            2017-03-30   83345306               Téléphone
10023       2016-02-03   70993496             Automatique
            2016-02-08   71169146               Téléphone
            2016-04-08   72963744               Téléphone
            2016-05-09   73770436               Téléphone
            2016-07-06   75416978               Téléphone
            2016-10-12   77868812               Téléphone
10025       2014-10-27   57045898               Téléphone
10027       2015-09-08   66168882             Automatique
10033       2016-03-02   71866090               Téléphone
            2016-03-08   72021978               Téléphone
            2016-06-07   74619430               Téléphone
10034       2016-10-18   78097774             Automatique
            2016-11-21   79087650               Téléphone
            2017-10-19   88816958             Automatique
10037       2016-02-02   70979254             Automatique
10040       2016-07-25   75823102             Automatique
            2017-06-14   85398850             Automatique
10042       2016-09-15   77034534             Automatique
            2016-10-11   77797196               Téléphone
10052       2015-06-24   64360738               Téléphone
10056       2016-09-13   76938778             Automatique
            2016-10-12   77849866               Téléphone

                                                                             COMMENTAIRE_BI  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876                                                         .
            2017-01-19   81119814                                                    ARM VE
            2017-02-01   81505320                           A-M / VISITE / REPORT AG. 02/02
10015       2015-11-12   68333220                                                         .
            2016-07-25   75830488                                                         .
10017       2016-12-23   80266556                                  A-M / VISITE D ENTRETIEN
10021       2017-03-20   83022676         MATIN VE A CONFIRMER /MESSAGE REPONDEUR LE 20....
            2017-03-30   83345306                                                    am  ve
10023       2016-02-03   70993496                                                         .
            2016-02-08   71169146                               DES 14H -- VISITE ENTRETIEN
            2016-04-08   72963744         DES 14H -- REMPL DDI97549740 SUIVANT DEVIS - P...
            2016-05-09   73770436                                                     FUITE
            2016-07-06   75416978          MATIN//REMPLAC FLEX DDI94994123+FLEX DDI94994121
            2016-10-12   77868812            APRES-MIDI / ECS MAIS PAS CHAUFFAGE T.A. A 24°
10025       2014-10-27   57045898                                        AM/BRUIT D EAU RAD
10027       2015-09-08   66168882                                                         .
10033       2016-03-02   71866090         MATIN//REMPL BALLON DDI8665527+V3V+ACTIONNEUR/...
            2016-03-08   72021978             DES 14H****  /vu avec cl/envoyer cs/eau tiède
            2016-06-07   74619430                                  A.M - VISITE D'ENTRETIEN
10034       2016-10-18   78097774                                                         .
            2016-11-21   79087650                                                    ARM VE
            2017-10-19   88816958                                                         .
10037       2016-02-02   70979254                                                         .
10040       2016-07-25   75823102                                                         .
            2017-06-14   85398850                                                         .
10042       2016-09-15   77034534                                                         .
            2016-10-11   77797196                              AM VE REPORT CLIENT DU 14.10
10052       2015-06-24   64360738                                                         .
10056       2016-09-13   76938778                                                         .
            2016-10-12   77849866                   MATINEE / DEFAUT BRULEUR - PANNE TOTALE

                                         SS_TR_FLAG TYPE_UT GRAVITE  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876                 N    UT01       -
            2017-01-19   81119814                 N    UT01       -
            2017-02-01   81505320                 N    UT01       -
10015       2015-11-12   68333220                 N    UT01       -
            2016-07-25   75830488                 N    UT01       -
10017       2016-12-23   80266556                 N    UT01       -
10021       2017-03-20   83022676                 N    UT01       -
            2017-03-30   83345306                 N    UT01       -
10023       2016-02-03   70993496                 N    UT01       -
            2016-02-08   71169146                 N    UT01       -
            2016-04-08   72963744                 N    UT02      PP
            2016-05-09   73770436                 N    UT02      PP
            2016-07-06   75416978                 N    UT02      PP
            2016-10-12   77868812                 N    UT02      PT
10025       2014-10-27   57045898                 N    UT02      PP
10027       2015-09-08   66168882                 N    UT01       -
10033       2016-03-02   71866090                 N    UT02      PP
            2016-03-08   72021978                 N    UT02      PP
            2016-06-07   74619430                 N    UT01      PP
10034       2016-10-18   78097774                 N    UT01       -
            2016-11-21   79087650                 N    UT01       -
            2017-10-19   88816958                 N    UT01       -
10037       2016-02-02   70979254                 N    UT01       -
10040       2016-07-25   75823102                 N    UT01       -
            2017-06-14   85398850                 N    UT01       -
10042       2016-09-15   77034534                 N    UT01       -
            2016-10-11   77797196                 N    UT01       -
10052       2015-06-24   64360738                 N    UT01       -
10056       2016-09-13   76938778                 N    UT01       -
            2016-10-12   77849866                 N    UT02      PT

                                          RESOURCE_ID SCHEDULED_START_DATE  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876         102107471.0           2017-01-19
            2017-01-19   81119814         100000747.0           2017-02-02
            2017-02-01   81505320         102107471.0           2017-03-01
10015       2015-11-12   68333220         101895406.0           2015-11-26
            2016-07-25   75830488         102967936.0           2016-09-16
10017       2016-12-23   80266556         100000115.0           2017-02-13
10021       2017-03-20   83022676         103379105.0           2017-03-29
            2017-03-30   83345306         103379105.0           2017-04-03
10023       2016-02-03   70993496         101835384.0           2016-02-17
            2016-02-08   71169146         102072460.0           2016-03-02
            2016-04-08   72963744         102072460.0           2016-04-28
            2016-05-09   73770436         101517327.0           2016-05-11
            2016-07-06   75416978         101662362.0           2016-07-27
            2016-10-12   77868812         100000146.0           2016-10-14
10025       2014-10-27   57045898         101453303.0           2014-10-28
10027       2015-09-08   66168882         102545762.0           2015-09-28
10033       2016-03-02   71866090         102357624.0           2016-03-07
            2016-03-08   72021978         100000148.0           2016-03-17
            2016-06-07   74619430         102357624.0           2016-06-23
10034       2016-10-18   78097774         101368283.0           2016-11-28
            2016-11-21   79087650         102357624.0           2016-12-14
            2017-10-19   88816958         103379105.0           2017-11-06
10037       2016-02-02   70979254         102357624.0           2016-02-29
10040       2016-07-25   75823102         102107471.0           2016-09-21
            2017-06-14   85398850         102967936.0           2017-07-03
10042       2016-09-15   77034534         102107471.0           2016-10-14
            2016-10-11   77797196         102107471.0           2016-10-25
10052       2015-06-24   64360738         101453303.0           2015-07-20
10056       2016-09-13   76938778         101453303.0           2016-11-04
            2016-10-12   77849866         100000148.0           2016-10-13

                                         SCHEDULED_END_DATE  target
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10003       2016-12-19   80032876                2017-01-19       0
            2017-01-19   81119814                2017-02-02       0
            2017-02-01   81505320                2017-03-01       0
10015       2015-11-12   68333220                2015-11-26       0
            2016-07-25   75830488                2016-09-16       0
10017       2016-12-23   80266556                2017-02-13       0
10021       2017-03-20   83022676                2017-03-29       0
            2017-03-30   83345306                2017-04-03       0
10023       2016-02-03   70993496                2016-02-17       0
            2016-02-08   71169146                2016-03-02       1
            2016-04-08   72963744                2016-04-28       1
            2016-05-09   73770436                2016-05-11       1
            2016-07-06   75416978                2016-07-27       1
            2016-10-12   77868812                2016-10-14       0
10025       2014-10-27   57045898                2014-10-28       1
10027       2015-09-08   66168882                2015-09-28       0
10033       2016-03-02   71866090                2016-03-07       1
            2016-03-08   72021978                2016-03-17       0
            2016-06-07   74619430                2016-06-23       0
10034       2016-10-18   78097774                2016-11-28       0
            2016-11-21   79087650                2016-12-14       0
            2017-10-19   88816958                2017-11-06       0

In [31]:
# are the observations in train in history ?
commmon_intervention_train = intervention_train.index.intersection(intervention_history.index)

In [32]:
commmon_intervention_test = intervention_test.index.intersection(intervention_history.index)

In [33]:
# train file is an extract from history file with target variable added
print(commmon_intervention_train.values.shape)
print(commmon_intervention_test.values.shape)

(4255404,)
(1339681,)

In [29]:
history_with_target = intervention_history.join(intervention_train['target'], how='left')

In [25]:
history_with_target[['target', 'time_delta', 'ACTUAL_START_DATE', 'ACTUAL_END_DATE', 'INCIDENT_TYPE_NAME', 'SCHEDULED_START_DATE', 'SCHEDULED_END_DATE',  'INCIDENT_STATUS_NAME', 'TYPE_BI', 'MOTIF_ANNULATION_CODE', 'MOTIF_ANNULATION_DESC']][0:50]

NameError: name 'history_with_target' is not defined

## cleaning data

In [39]:
# common observations in history and train ?
intervention_train.reset_index(inplace=True)
intervention_train.set_index(['INSTANCE_ID', 'CRE_DATE_GZL'], inplace=True)

In [40]:
intervention_test.reset_index(inplace=True)
intervention_test.set_index(['INSTANCE_ID', 'CRE_DATE_GZL'], inplace=True)

In [41]:
intervention_history.reset_index(inplace=True)
intervention_history.set_index(['INSTANCE_ID', 'CRE_DATE_GZL'], inplace=True)

In [42]:
# duplicates
#intervention_train.drop_duplicates(inplace=True)
intervention_train.index.duplicated()

array([False, False, False, ..., False, False, False], dtype=bool)

In [43]:
# several events can be created the same day for the same instance in the train test but not in the test set. 
# Sometime they look like duplicates and sometimes not.
# they can have a different target, apparently depending on the scheduled date
# as I connot establish a clear rule to apply on them, I will keep all lines except pure duplicates (index and values)

# todo? : extract feature: nb of lines for each couple (instance_id, creation_date) ? 
#    --> not useful since it's always only on in test set
intervention_train[intervention_train.index.duplicated(keep=False)]

                          INCIDENT_NUMBER    index  INCIDENT_TYPE_ID  \
INSTANCE_ID CRE_DATE_GZL
10150       2017-07-13           86270628   547368             10003
            2017-07-13           86283522   437576             10003
10218       2017-04-04           83463744   155703             10003
            2017-04-04           83486896   200778             10003
10270       2015-09-11           66311942  1047707             10005
            2015-09-11           66311982   345120             10005
10282       2016-12-22           80204534   883195             10003
            2016-12-22           80207526   987422             10003
10449       2016-07-05           75380652   553361             10005
            2016-07-05           75400802   563673             10003
11036       2016-10-04           77579664  1032764             10005
            2016-10-04           77579782   753724             10005
11037       2016-10-05           77589236   652586             10003
            2016-10-05           77594126   276024             10003
11521       2016-05-30           74396850   393774             10003
            2016-05-30           74412690   151524             10003
11580       2016-01-15           70389852   807939             10003
            2016-01-15           70393576   253882             10003
12092       2016-11-04           78604430   507906             10003
            2016-11-04           78604614   888498             10003
12665       2016-12-02           79466600   479404             10003
            2016-12-02           79485594   420252             10003
            2017-01-24           81243478   664408             10003
            2017-01-24           81249422   933882             10003
13573       2016-11-21           79081838   449765             10005
            2016-11-21           79100478   613443             10004
13610       2015-11-19           68533512   285460             10003
            2015-11-19           68558594   315991             10003
13820       2016-09-30           77482610   683922             10003
            2016-09-30           77486158   548737             10003
...                                   ...      ...               ...
52589999    2017-08-03           86743446   970264             10005
52591196    2017-10-05           88357786   121133             10003
            2017-10-05           88357830   923441             10003
52614988    2017-09-13           87633172   383119             10003
            2017-09-13           87633196   272214             10003
52795060    2017-09-06           87421340   253226             10003
            2017-09-06           87423872   498041             10005
52927391    2017-09-14           87683954   220922             10003
            2017-09-14           87685338   806168             10003
53505422    2017-10-05           88329326   959473             10003
            2017-10-05           88329452    40747             10003
            2017-10-05           88329640    18197             10003
53667222    2017-09-05           87391640   108102             10004
            2017-09-05           87392102   860343             10004
53956345    2017-09-07           87455612    70305             10003
            2017-09-07           87460232   315953             10005
54599527    2017-10-19           88817374   987764             10003
            2017-10-19           88819708   774001             10003
54795264    2017-10-06           88364416   405828             10003
            2017-10-06           88396144   502113             10003
55064478    2017-09-20           87853604   976858             10004
            2017-09-20           87869060  1020436             10004
55118690    2017-10-06           88364308   867005             10003
            2017-10-06           88365102   533859             10003
55313129    2017-10-11           88540310   252406             10003
            2017-10-11           88540392   535502             10005
55518090    2017-10-09           88451992   343327             10003
            2017-10-09           88452096   542190             10003
55826266    2017-10-06           88385290   926375             10003
            2017-10-06           88385376   496832             10003

                           INCIDENT_TYPE_NAME    TYPE_BI  NB_PASSAGE  \
INSTANCE_ID CRE_DATE_GZL
10150       2017-07-13              Dépannage  Dépannage         1.0
            2017-07-13              Dépannage  Dépannage         1.0
10218       2017-04-04              Dépannage  Dépannage         1.0
            2017-04-04              Dépannage  Dépannage         1.0
10270       2015-09-11              Entretien  Entretien         1.0
            2015-09-11              Entretien  Entretien         1.0
10282       2016-12-22              Dépannage  Dépannage         NaN
            2016-12-22              Dépannage  Dépannage         1.0
10449       2016-07-05              Entretien  Entretien         1.0
            2016-07-05              Dépannage  Dépannage         1.0
11036       2016-10-04              Entretien  Entretien         1.0
            2016-10-04              Entretien  Entretien         1.0
11037       2016-10-05              Dépannage  Dépannage         1.0
            2016-10-05              Dépannage  Dépannage         1.0
11521       2016-05-30              Dépannage  Dépannage         NaN
            2016-05-30              Dépannage  Dépannage         1.0
11580       2016-01-15              Dépannage  Dépannage         1.0
            2016-01-15              Dépannage  Dépannage         1.0
12092       2016-11-04              Dépannage  Dépannage         NaN
            2016-11-04              Dépannage  Dépannage         1.0
12665       2016-12-02              Dépannage  Dépannage         1.0
            2016-12-02              Dépannage  Dépannage         1.0
            2017-01-24              Dépannage  Dépannage         1.0
            2017-01-24              Dépannage  Dépannage         1.0
13573       2016-11-21              Entretien  Entretien         1.0
            2016-11-21    Dépannage+Entretien  Entretien         1.0
13610       2015-11-19              Dépannage  Dépannage         1.0
            2015-11-19              Dépannage  Dépannage         1.0
13820       2016-09-30              Dépannage  Dépannage         NaN
            2016-09-30              Dépannage  Dépannage         1.0
...                                       ...        ...         ...
52589999    2017-08-03              Entretien  Entretien         1.0
52591196    2017-10-05              Dépannage  Dépannage         NaN
            2017-10-05              Dépannage  Dépannage         1.0
52614988    2017-09-13              Dépannage  Dépannage         1.0
            2017-09-13              Dépannage  Dépannage         1.0
52795060    2017-09-06              Dépannage  Dépannage         1.0
            2017-09-06              Entretien  Entretien         1.0
52927391    2017-09-14              Dépannage  Dépannage         NaN
            2017-09-14              Dépannage  Dépannage         1.0
53505422    2017-10-05              Dépannage  Dépannage         1.0
            2017-10-05              Dépannage  Dépannage         NaN
            2017-10-05              Dépannage  Dépannage         1.0
53667222    2017-09-05    Dépannage+Entretien  Entretien         1.0
            2017-09-05    Dépannage+Entretien  Entretien         1.0
53956345    2017-09-07              Dépannage  Dépannage         1.0
            2017-09-07              Entretien  Entretien         1.0
54599527    2017-10-19              Dépannage  Dépannage         NaN
            2017-10-19              Dépannage  Dépannage         1.0
54795264    2017-10-06              Dépannage  Dépannage         1.0
            2017-10-06              Dépannage  Dépannage         1.0
55064478    2017-09-20    Dépannage+Entretien  Entretien         1.0
            2017-09-20    Dépannage+Entretien  Entretien         1.0
55118690    2017-10-06              Dépannage  Dépannage         NaN
            2017-10-06              Dépannage  Dépannage         1.0
55313129    2017-10-11              Dépannage  Dépannage         1.0
            2017-10-11              Entretien  Entretien         1.0
55518090    2017-10-09              Dépannage  Dépannage         1.0
            2017-10-09              Dépannage  Dépannage         1.0
55826266    2017-10-06              Dépannage  Dépannage         1.0
            2017-10-06              Dépannage  Dépannage         1.0

                          MILLESIME PROBLEM_CODE  PROBLEM_DESC  \
INSTANCE_ID CRE_DATE_GZL
10150       2017-07-13          NaN          NaN           NaN
            2017-07-13          NaN          NaN           NaN
10218       2017-04-04          NaN          NaN           NaN
            2017-04-04          NaN          NaN           NaN
10270       2015-09-11       2015.0          NaN           NaN
            2015-09-11       2015.0          NaN           NaN
10282       2016-12-22          NaN          NaN           NaN
            2016-12-22          NaN          NaN           NaN
10449       2016-07-05       2016.0          NaN           NaN
            2016-07-05          NaN          NaN           NaN
11036       2016-10-04       2016.0          NaN           NaN
            2016-10-04       2016.0          NaN           NaN
11037       2016-10-05          NaN          NaN           NaN
            2016-10-05          NaN          NaN           NaN
11521       2016-05-30          NaN          NaN           NaN
            2016-05-30          NaN          NaN           NaN
11580       2016-01-15          NaN          NaN           NaN
            2016-01-15          NaN          NaN           NaN
12092       2016-11-04          NaN          NaN           NaN
            2016-11-04          NaN          NaN           NaN
12665       2016-12-02          NaN          NaN           NaN
            2016-12-02          NaN           CH           NaN
            2017-01-24          NaN          NaN           NaN
            2017-01-24          NaN          NaN           NaN
13573       2016-11-21       2016.0          NaN           NaN
            2016-11-21       2016.0          NaN           NaN
13610       2015-11-19          NaN          NaN           NaN
            2015-11-19          NaN          NaN           NaN
13820       2016-09-30          NaN          NaN           NaN
            2016-09-30          NaN          NaN           NaN
...                             ...          ...           ...
52589999    2017-08-03       2017.0          NaN           NaN
52591196    2017-10-05          NaN          NaN           NaN
            2017-10-05          NaN          NaN           NaN
52614988    2017-09-13          NaN          NaN           NaN
            2017-09-13          NaN          NaN           NaN
52795060    2017-09-06          NaN          NaN           NaN
            2017-09-06       2017.0          NaN           NaN
52927391    2017-09-14          NaN          NaN           NaN
            2017-09-14          NaN          NaN           NaN
53505422    2017-10-05          NaN          NaN           NaN
            2017-10-05          NaN          NaN           NaN
            2017-10-05          NaN          NaN           NaN
53667222    2017-09-05       2017.0          NaN           NaN
            2017-09-05       2017.0          NaN           NaN
53956345    2017-09-07          NaN          NaN           NaN
            2017-09-07       2017.0          NaN           NaN
54599527    2017-10-19          NaN          NaN           NaN
            2017-10-19          NaN          NaN           NaN
54795264    2017-10-06          NaN          NaN           NaN
            2017-10-06          NaN          NaN           NaN
55064478    2017-09-20       2017.0          NaN           NaN
            2017-09-20       2017.0          NaN           NaN
55118690    2017-10-06          NaN          NaN           NaN
            2017-10-06          NaN          NaN           NaN
55313129    2017-10-11          NaN          NaN           NaN
            2017-10-11       2017.0          NaN           NaN
55518090    2017-10-09          NaN          NaN           NaN
            2017-10-09          NaN          NaN           NaN
55826266    2017-10-06          NaN          NaN           NaN
            2017-10-06          NaN          NaN           NaN

                          AUTEUR_INCIDENT ORIGINE_INCIDENT  \
INSTANCE_ID CRE_DATE_GZL
10150       2017-07-13              42405        Téléphone
            2017-07-13              36927        Téléphone
10218       2017-04-04               1614        Téléphone
            2017-04-04               1614        Téléphone
10270       2015-09-11               1614        Téléphone
            2015-09-11               1614        Téléphone
10282       2016-12-22               1614        Téléphone
            2016-12-22               1614        Téléphone
10449       2016-07-05              21231        Téléphone
            2016-07-05               1489        Téléphone
11036       2016-10-04               1488        Téléphone
            2016-10-04               1488        Téléphone
11037       2016-10-05               1488        Téléphone
            2016-10-05               1513        Téléphone
11521       2016-05-30              36124        Téléphone
            2016-05-30               1489        Téléphone
11580       2016-01-15               1619        Téléphone
            2016-01-15              24270        Téléphone
12092       2016-11-04               1614        Téléphone
            2016-11-04               1488        Téléphone
12665       2016-12-02               1488        Téléphone
            2016-12-02              36083        Téléphone
            2017-01-24               1486        Téléphone
            2017-01-24               1619        Téléphone
13573       2016-11-21               1513        Téléphone
            2016-11-21              36083        Téléphone
13610       2015-11-19              33257        Téléphone
            2015-11-19               1488        Téléphone
13820       2016-09-30               1614        Téléphone
            2016-09-30               1614        Téléphone
...                                   ...              ...
52589999    2017-08-03              29933        Téléphone
52591196    2017-10-05               6978        Téléphone
            2017-10-05              42885        Téléphone
52614988    2017-09-13               3311        Téléphone
            2017-09-13               3311        Téléphone
52795060    2017-09-06              36927        Téléphone
            2017-09-06               4950        Téléphone
52927391    2017-09-14              42143        Téléphone
            2017-09-14              42143        Téléphone
53505422    2017-10-05              36927        Téléphone
            2017-10-05              36927        Téléphone
            2017-10-05              36927        Téléphone
53667222    2017-09-05              39838        Téléphone
            2017-09-05              39838        Téléphone
53956345    2017-09-07              36927        Téléphone
            2017-09-07               9553        Téléphone
54599527    2017-10-19               2363        Téléphone
            2017-10-19              26361        Téléphone
54795264    2017-10-06              36927        Téléphone
            2017-10-06               5711        Téléphone
55064478    2017-09-20              39432        Téléphone
            2017-09-20               5771        Téléphone
55118690    2017-10-06              36927        Téléphone
            2017-10-06              36927        Téléphone
55313129    2017-10-11              36927        Téléphone
            2017-10-11              36927        Téléphone
55518090    2017-10-09              39591        Téléphone
            2017-10-09              39591        Téléphone
55826266    2017-10-06              36927        Téléphone
            2017-10-06              36927        Téléphone

                                                             COMMENTAIRE_BI  \
INSTANCE_ID CRE_DATE_GZL
10150       2017-07-13                      PLUS D EAU CHAUDE / 14H00-18H00
            2017-07-13            pièce OKéchangeur MTS61302409S 1H00 MATIN
10218       2017-04-04    s est mise à vibrer hier soir a tout coupé car...
            2017-04-04                                                  +EC
10270       2015-09-11                                  VE//REPORT DU 17.09
            2015-09-11                              14H//REPORT VE DU 17.09
10282       2016-12-22    NVX PROPRIET MR KERUZORE 0781588939//DEP PAYAN...
            2016-12-22    IMPERATIF PRENDRE CONTRAT SIGNE SUR PLACE/PBL ...
10449       2016-07-05                                                   VE
            2016-07-05                                    A.M - EN SECURITE
11036       2016-10-04               MATINEE / VISITE / REPORT CLIENT 04/10
            2016-10-04     APRES-MIDI / VISITE D ENTRETIEN  -- report 03/10
11037       2016-10-05                           MATINEE / PAS DE CHAUFFAGE
            2016-10-05                              REMPLACEMENT THERMOSTAT
11521       2016-05-30                                         ARM PLUS ESC
            2016-05-30                                         A.M - PAS EC
11580       2016-01-15    SDU05721000+05721200+S5744000 BAC SAMEDI 1 CLI...
            2016-01-15                                  en double avec Greg
12092       2016-11-04                                  +CHAUFFAGE - ECS OK
            2016-11-04               APRES-MIDI / PAS DE CHAUFFAGE - ECS OK
12665       2016-12-02     MATINEE / PAS DE CHAUFFAGE AU PLANCHER CHAUFFANT
            2016-12-02        ARM -  PAS DE CHAUFFAGE AU PLANCHER CHAUFFANT
            2017-01-24                                                AM PT
            2017-01-24                       POMPE CED3611371 2H00 DEVIS OK
13573       2016-11-21                                                    .
            2016-11-21                             ARM REMISE EN ROUTE + VE
13610       2015-11-19    ARM PAS D ETINCELLE - APPAREIL NE SE DECLENCHE...
            2015-11-19    A-M/ ARM PAS D ETINCELLE - APPAREIL NE SE DECL...
13820       2016-09-30                                                - +EC
            2016-09-30                                                  +EC
...                                                                     ...
52589999    2017-08-03                       AVANT 15H - FAIRE ENTRETIEN OK
52591196    2017-10-05                      POUR CLOTURE AR DEVIS FAIT - KS
            2017-10-05    SI POSSIBLE AVANT / PT - REMPL SONDE + TFI / D...
52614988    2017-09-13                         MATIN AIDE KP POSE CHAUDIERE
            2017-09-13                         MATIN AIDE KP POSE CHAUDIERE
52795060    2017-09-06    ARM FUITTE GOUTTE A GOUTTE DERRIER + CODE ERRE...
            2017-09-06                        VISITE + recharge fluide calo
52927391    2017-09-14        CLM/A 8H30 MISE EN ROUTE CHAUFFAGE IMPOSSIBLE
            2017-09-14        CLM/A 8H30 MISE EN ROUTE CHAUFFAGE IMPOSSIBLE
53505422    2017-10-05     MOTEUR POMPE + SOUPAPE DISPO MAG NGUYEN + SEIXAS
            2017-10-05     MOTEUR POMPE + SOUPAPE DISPO MAG NGUYEN + SEIXAS
            2017-10-05                            NGUYEN + SEIXAS FORMATION
53667222    2017-09-05                                                  DEP
            2017-09-05                            PAS DECS // CHANGER PIECE
53956345    2017-09-07    1er rdv AM / CH. s'est remise en sécurité / pr...
            2017-09-07                                              28/09 M
54599527    2017-10-19                                                    .

In [44]:
intervention_test[intervention_test.index.duplicated(keep=False)]

Empty DataFrame
Columns: [INCIDENT_NUMBER, index, INCIDENT_TYPE_ID, INCIDENT_TYPE_NAME, TYPE_BI, NB_PASSAGE, MILLESIME, PROBLEM_CODE, PROBLEM_DESC, AUTEUR_INCIDENT, ORIGINE_INCIDENT, COMMENTAIRE_BI, SS_TR_FLAG, TYPE_UT, GRAVITE, RESOURCE_ID, SCHEDULED_START_DATE, SCHEDULED_END_DATE]
Index: []

In [136]:
# check NA
intervention_train.isnull().sum()

INSTANCE_ID                   0
INCIDENT_NUMBER               0
INCIDENT_TYPE_ID              0
INCIDENT_TYPE_NAME            0
TYPE_BI                       0
NB_PASSAGE                27046
MILLESIME                292829
PROBLEM_CODE            1041360
PROBLEM_DESC            1048030
AUTEUR_INCIDENT               0
ORIGINE_INCIDENT            253
COMMENTAIRE_BI              515
SS_TR_FLAG                    0
TYPE_UT                       0
GRAVITE                       0
RESOURCE_ID                2350
SCHEDULED_START_DATE          0
SCHEDULED_END_DATE            0
CRE_DATE_GZL                  0
target                        0
dtype: int64

In [137]:
def nan_check(series):
    print(series.name + '\n')
    print(series.isnull().sum())
    print(series.unique())
    print(series.value_counts())
    print('\n' * 3)

In [138]:
columns_with_nan = intervention_train.isnull().any()

In [139]:
intervention_train.loc[:, columns_with_nan].head(100)

,NB_PASSAGE,MILLESIME,PROBLEM_CODE,PROBLEM_DESC,ORIGINE_INCIDENT,COMMENTAIRE_BI,RESOURCE_ID
0,1.0,2017.0,NaN,NaN,Téléphone,.,101629356.0
1,1.0,2017.0,NaN,NaN,Téléphone,1er rdv,100206988.0
2,2.0,2013.0,NaN,NaN,Téléphone,16H45-VE,102156488.0
3,1.0,2014.0,NaN,NaN,Téléphone,.,102334599.0
4,1.0,2016.0,NaN,NaN,Téléphone,VTE 2016 APRES 9H,102460713.0
5,1.0,2017.0,NaN,NaN,Téléphone,ARM : SERENITE DV. RECUP.CONTRAT. VERIF TYPE A...,102983952.0
6,1.0,NaN,NaN,NaN,Téléphone,PAS D EAU CHAUDE + PAS DE PRESSION VU LE 26.0...,100058901.0
7,1.0,2016.0,NaN,NaN,Téléphone,.,100663106.0
8,1.0,2017.0,NaN,NaN,Téléphone,ARM VE,102814875.0
9,1.0,2017.0,NaN,NaN,Automatique,.,103362101.0
10,1.0,NaN,NaN,NaN,Téléphone,PEU DECS,103194044.0
11,1.0,2017.0,NaN,NaN,Téléphone,.,103194044.0
12,1.0,2017.0,NaN,NaN,Téléphone,ENTRETIEN 2017 POUR ROMAIN,100070892.0
13,2.0,2017.0,NaN,NaN,Téléphone,ENTRETIEN-DESCENDRE RUE DE L EGLISE-AVANT CENT...,103413122.0
14,1.0,2014.0,NaN,NaN,Téléphone,.,101786373.0
15,1.0,NaN,NaN,NaN,Téléphone,RMPLT EXTRACTEUR SUIVANT DEVIS,100051883.0
16,1.0,NaN,NaN,NaN,Téléphone,REMPLACEMENT DU BOUTON,100016820.0
17,1.0,2016.0,NaN,NaN,Automatique,.,100000920.0
18,1.0,2016.0,NaN,NaN,Automatique,MAG CACHE CACHE AVERTI / OK 9H30-12H30,100043869.0
19,1.0,2016.0,NaN,NaN,Automatique,MAG .,100001119.0
20,1.0,2016.0,NaN,NaN,Automatique,.,102321593.0
21,1.0,2016.0,NaN,NaN,Automatique,.,100051883.0
22,1.0,2016.0,NaN,NaN,Téléphone,VEC - VIENT EXPRES,100000696.0
23,1.0,NaN,NaN,NaN,Téléphone,"DEPUIS VE 09/08 AFS, NE TIENT PAS LA PRESSION",102513749.0
24,1.0,2016.0,NaN,NaN,Automatique,.,101995434.0
25,1.0,2016.0,NaN,NaN,Automatique,....AVT 11H,100000917.0
26,1.0,NaN,NaN,NaN,Téléphone,TEL AVANT AU 0612450368 // TRAVAUX DEVIS N° 7...,102570769.0
27,1.0,NaN,NaN,NaN,Téléphone,SUITE COUPURE DE COURANT REVOIR REPROGRAMMATION,100001138.0
28,1.0,2016.0,NaN,NaN,Automatique,8H30 OK VE CHLOE,100000306.0
29,1.0,2017.0,NaN,NaN,Automatique,ve matin,100000921.0
...,...,...,...,...,...,...,...
70,1.0,NaN,NaN,NaN,Téléphone,PT,100879141.0
71,1.0,2015.0,NaN,NaN,Téléphone,REVISION + CONTRAT - MENSUALISATION (VOIR CHAN...,100540088.0
72,1.0,2015.0,NaN,NaN,Téléphone,.,100757120.0
73,1.0,2016.0,NaN,NaN,Automatique,.,NaN
74,1.0,2016.0,NaN,NaN,Téléphone,SAUF ENTRE 16H ET 16H30,100938139.0
75,NaN,NaN,NaN,NaN,Téléphone,.,100711132.0
76,1.0,NaN,NaN,NaN,Téléphone,FUITE CHAUD. DESCEND EN PRESSION,100928134.0
77,1.0,NaN,NaN,NaN,Téléphone,EXECUTION DEVIS / PRENDRE COORDONEE PROPRIETAIRE,100001303.0
78,1.0,2016.0,NaN,NaN,Automatique,.,100478089.0
79,1.0,2017.0,NaN,NaN,Téléphone,ARM VE,100436082.0
80,2.0,2016.0,NaN,NaN,Téléphone,ARM VE,100245039.0
81,1.0,2017.0,NaN,NaN,Automatique,ok ve dispo a partir 16h30,103185036.0
82,1.0,2016.0,NaN,NaN,Automatique,.,100024830.0
83,1.0,2017.0,NaN,NaN,Téléphone,visite OK AM,102155488.0
84,1.0,NaN,NaN,NaN,Téléphone,REMPLACER PIECE OCCASION PAR NEUVE/DEBUT A.MID...,100136945.0
85,1.0,2017.0,NaN,NaN,Automatique,.,100457084.0
86,1.0,2017.0,NaN,NaN,Téléphone,24/03/2017 MATIN OK CLTappareil plus de 15ans,102942928.0
87,1.0,2017.0,NaN,NaN,Automatique,.,100700111.0
88,1.0,NaN,NaN,NaN,Téléphone,SUIVANT DEVIS N° 2014313 POSE T-A DELTA DORE +...,100038858.0
89,1.0,2015.0,NaN,NaN,Téléphone,VE OK,102067454.0
90,1.0,2016.0,NaN,NaN,Automatique,.,100016819.0
91,1.0,NaN,NaN,NaN,Téléphone,RPLMT DE LA V3V VIE7824699,100051868.0
92,1.0,2017.0,NaN,NaN,Téléphone,MESSAGE PORTABLE REMP. PIECES SUIVANT DEVIS //...,102301587.0
93,1.0,2017.0,NaN,NaN,Téléphone,OK ENTRETIEN CAT,100000309.0
94,1.0,NaN,NaN,NaN,Téléphone,APRES 11H-JOINT CAPTEUR FUMEE A REMPLACER,100014794.0
95,1.0,2017.0,NaN,NaN,Téléphone,2017-OK,101513325.0
96,1.0,2017.0,NaN,NaN,Téléphone,.,100000897.0
97,NaN,NaN,NaN,NaN,Téléphone,X,100000676.0
98,1.0,2017.0,NaN,NaN,Automatique,.,103259077.0
99,1.0,2017.0,NaN,NaN,Automatique,VE du 12.10 matin annulée interne le 10.10 car...,100038861.0

In [52]:
intervention_train.loc[:, columns_with_nan].apply(nan_check, axis=0)

NB_PASSAGE

27046
[1.0 2.0 nan 3.0 4.0 5.0 6.0]
1.0    952087
2.0     64767
3.0      3957
4.0       166
5.0         6
6.0         1
Name: NB_PASSAGE, dtype: int64




MILLESIME

292829
[2017.0 2015.0 2016.0 nan 2014.0 2013.0 2018.0 2012.0]
2016.0    379902
2017.0    281321
2015.0     71502
2014.0     20021
2013.0      2408
2012.0        36
2018.0        11
Name: MILLESIME, dtype: int64




PROBLEM_CODE

1041360
[nan 'FE' 'EC' 'CH' 'AB' 'SC' 'TA' 'PU' 'AL' 'FG' 'PR' 'DJ' 'VM' 'VE']
FE    1517
CH    1307
EC    1301
SC    1217
AB     492
PR     363
TA     157
AL      84
FG      80
VE      74
DJ      45
PU      30
VM       3
Name: PROBLEM_CODE, dtype: int64




PROBLEM_DESC

1048030
[nan]
Series([], Name: PROBLEM_DESC, dtype: int64)




ORIGINE_INCIDENT

253
['Automatique' 'Téléphone' 'Courrier' 'Venue client' 'Mail' nan 'Répondeur'
 'Télé-alarme' 'Internet']
Téléphone       673242
Automatique     372626
Répondeur          851
Courrier           466
Mail               263
Venue client       262
Internet            57
Télé-alarme         10
Name: ORIGINE_INCIDENT, dtype: int64




COMMENTAIRE_BI

515
['.' 'ARM VE' 'A-M / VISITE / REPORT AG. 02/02' ...,
 'DOSSIER 1529/17 SS GARANTIE'
 'PANNE TOTALE // FIOUL OK // G CONSEILLE DE CHANGER PILES THERMOSTAT'
 'T. FUITE SUR CHAUDIERE + SOUSCRIPTION CONTRAT']
.                                                                                   363747
ARM VE                                                                               12980
VE OK                                                                                 6146
VE                                                                                    5928
CONFIRME                                                                              5200
ENTRETIEN                                                                             4452
PANNE TOTALE                                                                          4071
OK                                                                                    3307
PAS DE CHAUFFAGE                                                                      2698
VE CONFIRMEE                                                                          2632
RDV OK                                                                                2368
ARM : SERENITE DV. RECUP. CONTRAT. VERIF TYPE APPAREIL. RECTIF TVA SI NECESSAIRE      2332
RDV CONFIRME                                                                          1934
VE 2016                                                                               1835
FUITE                                                                                 1745
ARM : SERENITE DV. RECUP.CONTRAT. VERIF TYPE APPAREIL. RECTIF TVA SI NECESSAIRE       1721
PT                                                                                    1614
VISITE OK                                                                             1598
+15                                                                                   1385
VE 2017                                                                               1298
Non confirmation de RDV                                                               1211
FUITE D EAU                                                                           1197
ENTRETIEN CONFIRME                                                                    1182
MATIN                                                                                 1103
ARM : ESSENTIEL DV.RECUP. CONTRAT. VERIF TYPE APPAREIL. RECTIF TVA SI NECESSAIRE      1011
VE CONF                                                                                984
OK CLIENT                                                                              969
ARM SUCCESSEUR. PRISE CTRT. CTRT TRANSMIS.                                             928
ARM                                                                                    844
IMPERATIF                                                                              838
                                                                                     ...
ARM FUITES IMPORTANTE BALLON LA CLIENTE LAISSE LA CLE SUR PORTE DE CAVE                  1
IMPOSSIBLE A DEMARRER                                                                    1
ARM REMPLACE VE DU 11/09                                                                 1
DES 14H**** / VISITE / REPORT 16/12 + REPORT CLIENT 10/01                                1
ARM : SERENITE DV. RECUP. CONTRAT. + INSTALLER NOUVELLE ZEN BOX VU YVON                  1
DEJA REMIS 1ER CLT A MIDI                                                                1
PANNE TOTALE+PROPO CONTRAT                                                               1
***APRES 16H00 RGS 903412 / RGS 903413 REDUCTION PVC                                     1
fuite de partout                                                                         1
0383571507 - BRUIT PAS D EAU CHAUDE                                                      1
SE VIDE MATIN                                                                            1
APRES 10 H 00 - VE 2016 + RECUPERER CONTRAT SIGNE                                        1
OK CLIENTE PRESENTE-SONNER DANS LE COULOIR-ENTRETIEN ET CONTRAT                          1
VE 2016+ RECUP CONTRAT + ENVOI COPIE DE LA FACTURE PAR MAIL                              1
08H15 PERS SUR PLACE EXPRES / RECUP CT SIGNE + VISITE                                    1
VE2017 APRES 10H                                                                         1
VOIR CHANGER LA CHAUDIERE OU NON                                                         1
EXECUTION DEVIS/ OK PIECE                                                                1
VE A RESPECTER / ECS NE FONCTIONNE PAS                                                   1
VE +MANO SUIVANT DEVIS                                                                   1
FUITE ROBINETS                                                                           1
8h45 v2014                                                                               1
TEL 30 MNS AVT 0649191525 //ENTRETIEN // OK CLIENT // ML                                 1
ARM FUITE GAG SUR CHAUDIERE LUDOVIC B                                                    1
SE MET TOUJOURS EN SECU CLIENTE TRES MECONTENTE LS/04/07                                 1
PLUS DE CHAUFFAGE // CG                                                                  1
PEC DES QU ELLE STOPPE CHAUFFAGE                                                         1
MATINEE / VISITE / REPORT AG. 25/01 / FAIRE VE ET REMONTAGE DE L'AUTRE APPAREIL          1
SE DEPLACE SPECIALEMENT *****AVANT 10H                                                   1
ARM CLIENTE ANNUL                                                                        1
Name: COMMENTAIRE_BI, Length: 422228, dtype: int64




RESOURCE_ID

2350
[102107471.0 100000747.0 101895406.0 ..., 100043860.0 103596172.0
 103550165.0]
100584105.0    1648
101582341.0    1599
100499085.0    1571
100000746.0    1488
100583105.0    1484
100058909.0    1390
100689112.0    1322
101391285.0    1281
101982429.0    1277
102201509.0    1240
102703827.0    1234
100583111.0    1229
100583109.0    1216
100583106.0    1204
100497085.0    1191
103025973.0    1190
100000834.0    1189
100051867.0    1172
100016828.0    1171
100001710.0    1154
100017810.0    1142
100747114.0    1140
100000271.0    1137
101833383.0    1122
100016829.0    1117
102492747.0    1114
100000309.0    1114
100000845.0    1095
101779372.0    1088
102830899.0    1085
               ...
102301586.0       1
103612173.0       1
101409292.0       1
100859133.0       1
102300586.0       1
101458307.0       1
100689110.0       1
100689114.0       1
102327594.0       1
100689115.0       1
102219517.0       1
102037453.0       1
100952171.0       1
103661197.0       1
102218518.0       1
420399.0          1
102394661.0       1
102636797.0       1
102525756.0       1
102243546.0       1
103670201.0       1
102133481.0       1
101170261.0       1
102133482.0       1
100136952.0       1
102198508.0       1
102185505.0       1
422202.0          1
103445130.0       1
103554161.0       1

Name: RESOURCE_ID, Length: 4032, dtype: int64

NB_PASSAGE          None
MILLESIME           None
PROBLEM_CODE        None
PROBLEM_DESC        None
ORIGINE_INCIDENT    None
COMMENTAIRE_BI      None
RESOURCE_ID         None
dtype: object

**NB_PASSAGE** : nan will be replaced by value 1
<br>
**MILLESIME** : extract year from creation event date
<br>
**PROBLEM_CODE** : added a modality 'NC' for 'not communicated'
<br>
**PROBLEM_DESC** : variable is always nan, it will be removed
<br>
**ORIGINE_INCIDENT** : modality 'telephone' will be applied (could run some chi square test to see if there is any different between telephone and automatique regarding target variable)
<br>
**COMMENTAIRE_BI** : nan will be replaced by '.'
<br>
**RESOURCE_ID** : nan will be replaced by 0

In [7]:
# rewrite in a function using fillna (improve readability)

intervention_train.loc[intervention_train.NB_PASSAGE.isnull(), 'NB_PASSAGE'] = 1
intervention_train.loc[intervention_train.PROBLEM_CODE.isnull(), 'PROBLEM_CODE'] = 'NC'
intervention_train.loc[intervention_train.ORIGINE_INCIDENT.isnull(), 'ORIGINE_INCIDENT'] = 'NAN'
intervention_train.loc[intervention_train.COMMENTAIRE_BI.isnull(), 'COMMENTAIRE_BI'] = '.'
intervention_train.loc[intervention_train.RESOURCE_ID.isnull(), 'RESOURCE_ID'] = 0

In [128]:
intervention_train.index

RangeIndex(start=0, stop=1048030, step=1)

In [168]:
intervention_train.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1048030 entries, (10003, 2016-12-19 00:00:00) to (57307101, 2017-10-19 00:00:00)
Data columns (total 18 columns):
INCIDENT_NUMBER         1048030 non-null int64
INCIDENT_TYPE_ID        1048030 non-null int64
INCIDENT_TYPE_NAME      1048030 non-null object
TYPE_BI                 1048030 non-null object
NB_PASSAGE              1048030 non-null float64
MILLESIME               1048030 non-null int64
PROBLEM_CODE            1048030 non-null object
PROBLEM_DESC            0 non-null float64
AUTEUR_INCIDENT         1048030 non-null int64
ORIGINE_INCIDENT        1048030 non-null object
COMMENTAIRE_BI          1048030 non-null object
SS_TR_FLAG              1048030 non-null object
TYPE_UT                 1048030 non-null object
GRAVITE                 1048030 non-null object
RESOURCE_ID             1048030 non-null int64
SCHEDULED_START_DATE    1048030 non-null datetime64[ns]
SCHEDULED_END_DATE      1048030 non-null datetime64[ns]
target                  1048030 non-null int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(8)
memory usage: 153.5+ MB

In [95]:
#TODO: create a function to do that
# not used here
nb_missing = sum(intervention_train.MILLESIME.isnull())
distrib = intervention_train.MILLESIME.value_counts()
weigths = distrib / distrib.sum()

fill_values = np.random.choice(distrib.index, 
                                 nb_missing,
                                 p=weigths)

intervention_train.loc[intervention_train.MILLESIME.isnull(), 'MILLESIME'] = fill_values

pd.Series(fill_values).value_counts()

In [8]:
#fill the missing millesime by year of creation date
missing_millesime = intervention_train.MILLESIME.isnull()
intervention_train.loc[missing_millesime, 'MILLESIME'] = intervention_train.loc[missing_millesime, 'CRE_DATE_GZL'].apply(lambda x: x.year)

In [9]:
intervention_train.drop('PROBLEM_DESC', axis=1, inplace=True)

In [10]:
# check no more missing values
intervention_train.isnull().sum()

INSTANCE_ID             0
INCIDENT_NUMBER         0
INCIDENT_TYPE_ID        0
INCIDENT_TYPE_NAME      0
TYPE_BI                 0
NB_PASSAGE              0
MILLESIME               0
PROBLEM_CODE            0
AUTEUR_INCIDENT         0
ORIGINE_INCIDENT        0
COMMENTAIRE_BI          0
SS_TR_FLAG              0
TYPE_UT                 0
GRAVITE                 0
RESOURCE_ID             0
SCHEDULED_START_DATE    0
SCHEDULED_END_DATE      0
CRE_DATE_GZL            0
target                  0
dtype: int64

In [11]:
# change type of int variables (from float to int, possible because no more nans)
intervention_train['MILLESIME'] = intervention_train['MILLESIME'].astype(int)
intervention_train['RESOURCE_ID'] = intervention_train['RESOURCE_ID'].astype(int)

### check ORIGINE_INCIDENT is not independant from target (it is not)

on the full table

In [114]:
import scipy

In [112]:
full_contingency = np.array(pd.crosstab(index=intervention_train['target'], columns=intervention_train['ORIGINE_INCIDENT']))

In [117]:
#origine incident is not independant from target
p_value = scipy.stats.chi2_contingency(full_contingency)[1]
print(p_value)

0.0

In [122]:
telephone_or_auto = intervention_train['ORIGINE_INCIDENT'].isin(['Téléphone', 'Automatique'])

In [123]:
intervention_train_extract = intervention_train.loc[telephone_or_auto, :]

only on auto or telephone modalities

In [124]:
limited_contingency =  np.array(pd.crosstab(index=intervention_train_extract['target'], columns=intervention_train_extract['ORIGINE_INCIDENT']))

In [142]:
p_value = scipy.stats.chi2_contingency(limited_contingency)[1]
print(p_value)

0.0

Origine_incident is correlated to target.
Question: what to do in test set ?
- option 1: infer from a model
- option 2: create a specific modality <---
- option 3: fill with specific value
- option 4: fill randomly

In [127]:
sum(intervention_test.ORIGINE_INCIDENT.isnull())

68

## Recreate target and complete training data with history

In [10]:
intervention_history.columns

Index(['INSTANCE_ID', 'INCIDENT_NUMBER', 'DATE_SAISIE_RETOUR',
       'INCIDENT_TYPE_ID', 'INCIDENT_TYPE_NAME', 'INCIDENT_STATUS_ID',
       'INCIDENT_STATUS_NAME', 'INCIDENT_STATUS_CODE', 'INCIDENT_CLOSED_FLAG',
       'TYPE_BI', 'NB_PASSAGE', 'MILLESIME', 'PROBLEM_CODE', 'PROBLEM_DESC',
       'MOTIF_A_REVOIR', 'AUTEUR_INCIDENT', 'ORIGINE_INCIDENT',
       'COMMENTAIRE_BI', 'SS_TR_FLAG', 'TYPE_UT', 'GRAVITE',
       'COMMENTAIRE_FIN_INTERV', 'MOTIF_ANNULATION_CODE',
       'MOTIF_ANNULATION_DESC', 'RESOURCE_ID', 'SCHEDULED_START_DATE',
       'SCHEDULED_END_DATE', 'ACTUAL_START_DATE', 'ACTUAL_END_DATE',
       'CRE_DATE_GZL'],
      dtype='object')

In [7]:
# delete canceled appointments from the training ?
# TODO: put a boolean in a preprocessing to do so or not
intervention_history.sort_values(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER'], inplace=True)

In [8]:
groups = intervention_history.groupby('INSTANCE_ID')

In [9]:
get_time_delta = lambda s: s.diff(1).shift(-1)

In [18]:
#time_delta = groups.CRE_DATE_GZL.transform(get_time_delta)

In [19]:
#intervention_history['time_delta'] = time_delta

In [20]:
#intervention_history.reset_index(inplace=True)

In [11]:
intervention_history['time_delta'] = groups.ACTUAL_START_DATE.transform(get_time_delta)

In [14]:
intervention_history['next_incident_type'] = groups.INCIDENT_TYPE_NAME.transform(lambda s: s.shift(-1))

In [23]:
intervention_history['target_test'] = intervention_history['time_delta'].between(pd.Timedelta('1 days'), pd.Timedelta('182 days')) \
                                        & (intervention_history['next_incident_type'] != 'Entretien') \
                                        & intervention_history['MOTIF_ANNULATION_CODE'].isnull()

In [29]:
intervention_train.reset_index(inplace=True)
intervention_train.set_index(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER'], inplace=True)

In [30]:
intervention_history.reset_index(inplace=True)
intervention_history.set_index(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER'], inplace=True)

In [31]:
intervention_train.sort_index(inplace=True)
intervention_history.sort_index(inplace=True)

In [32]:
history_with_target = intervention_history.join(intervention_train['target'], how='left')

In [36]:
history_with_target.loc[~history_with_target.target.isnull(), ['target', 'target_test','time_delta', 'next_incident_type', 'MOTIF_ANNULATION_CODE', 'ACTUAL_START_DATE', 'ACTUAL_END_DATE', 'INCIDENT_TYPE_NAME', 'SCHEDULED_START_DATE', 'SCHEDULED_END_DATE',  'INCIDENT_STATUS_NAME', 'TYPE_BI', 'MOTIF_ANNULATION_CODE', 'MOTIF_ANNULATION_DESC']][50:100]

                                          target  target_test time_delta  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10135       2017-09-04   87371802            1.0         True    10 days
            2017-09-11   87530552            0.0        False   179 days
10145       2016-03-01   71826460            0.0        False        NaT
            2016-03-31   72726524            0.0        False        NaT
10149       2015-05-15   63191770            0.0        False        NaT
10150       2016-05-12   73912140            1.0         True   141 days
            2016-11-02   78499460            0.0        False   200 days
            2017-04-19   83929378            1.0         True    52 days
            2017-07-13   86270628            1.0         True     2 days
                         86283522            1.0        False        NaT
10151       2016-06-06   74581562            0.0        False        NaT
            2016-09-15   77017352            0.0        False    67 days
            2016-11-16   78978080            0.0        False   196 days
            2017-05-30   84968400            1.0         True    66 days
            2017-09-04   87364680            1.0        False        NaT
            2017-09-05   87403348            0.0        False        NaT
10157       2015-09-25   66731406            0.0        False        NaT
            2016-08-08   76127670            0.0        False        NaT
10158       2015-09-25   66731456            0.0        False        NaT
10161       2016-06-23   75092972            0.0        False   300 days
            2017-05-30   84966748            1.0         True   160 days
10162       2016-11-07   78679328            0.0        False   364 days
10173       2016-01-18   70431504            1.0         True    42 days
            2016-03-01   71824972            0.0        False        NaT
10182       2017-10-17   88747882            0.0        False        NaT
10186       2016-02-29   71775132            0.0        False        NaT
            2016-12-15   79963306            0.0        False        NaT
            2017-01-16   80960260            0.0        False   210 days
10188       2016-12-15   79959630            0.0        False        NaT
10196       2016-09-15   77023356            1.0         True    34 days
            2016-11-08   78728066            0.0        False        NaT
10200       2016-12-19   80067172            1.0         True    40 days
            2017-02-24   82241984            1.0        False        NaT
            2017-04-27   84148728            1.0         True    34 days
            2017-06-01   85044580            1.0         True    41 days
            2017-07-08   86138630            1.0        False        NaT
10202       2015-04-20   62531692            1.0         True     6 days
            2015-04-23   62645658            0.0        False   281 days
            2016-02-01   70916040            1.0         True   174 days
            2016-07-25   75804950            1.0        False     0 days
            2016-09-21   77204308            0.0         True     5 days
10203       2016-12-23   80266514            0.0        False        NaT
            2017-03-02   82408854            0.0        False        NaT
            2017-04-03   83448848            1.0         True    22 days
            2017-05-23   84812254            1.0         True   116 days
            2017-09-13   87627698            0.0        False        NaT
10218       2017-04-04   83463744            0.0        False     0 days
                         83486896            0.0        False        NaT
10223       2016-07-21   75765602            0.0        False   376 days
            2017-07-10   86169274            0.0        False   197 days

                                                     next_incident_type  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10135       2017-09-04   87371802                             Dépannage
            2017-09-11   87530552                             Entretien
10145       2016-03-01   71826460                             Entretien
            2016-03-31   72726524                                   NaN
10149       2015-05-15   63191770                                   NaN
10150       2016-05-12   73912140                             Dépannage
            2016-11-02   78499460                             Entretien
            2017-04-19   83929378                             Dépannage
            2017-07-13   86270628                             Dépannage
                         86283522                                   NaN
10151       2016-06-06   74581562                             Entretien
            2016-09-15   77017352                             Entretien
            2016-11-16   78978080                             Entretien
            2017-05-30   84968400                             Dépannage
            2017-09-04   87364680                             Dépannage
            2017-09-05   87403348                                   NaN
10157       2015-09-25   66731406                             Entretien
            2016-08-08   76127670         Démarchage Dom. successeur/AG
10158       2015-09-25   66731456                                   NaN
10161       2016-06-23   75092972                             Entretien
            2017-05-30   84966748                             Dépannage
10162       2016-11-07   78679328                             Entretien
10173       2016-01-18   70431504                             Dépannage
            2016-03-01   71824972                                   NaN
10182       2017-10-17   88747882                             Entretien
10186       2016-02-29   71775132                             Entretien
            2016-12-15   79963306                             Entretien
            2017-01-16   80960260                  WEBDépan : dépannage
10188       2016-12-15   79959630                                   NaN
10196       2016-09-15   77023356                             Dépannage
            2016-11-08   78728066                                   NaN
10200       2016-12-19   80067172                             Dépannage
            2017-02-24   82241984                             Dépannage
            2017-04-27   84148728                             Dépannage
            2017-06-01   85044580                             Dépannage
            2017-07-08   86138630                                   NaN
10202       2015-04-20   62531692                             Dépannage
            2015-04-23   62645658                             Entretien
            2016-02-01   70916040                             Dépannage
            2016-07-25   75804950                  Devis et Prop. Ciale
            2016-09-21   77204308                  Devis et Prop. Ciale
10203       2016-12-23   80266514                             Entretien
            2017-03-02   82408854                             Entretien
            2017-04-03   83448848                             Dépannage
            2017-05-23   84812254                             Dépannage
            2017-09-13   87627698                                   NaN
10218       2017-04-04   83463744                             Dépannage
                         83486896                                   NaN
10223       2016-07-21   75765602                             Entretien
            2017-07-10   86169274                             Dépannage

                                         MOTIF_ANNULATION_CODE  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10135       2017-09-04   87371802                          NaN
            2017-09-11   87530552                          NaN
10145       2016-03-01   71826460                            A
            2016-03-31   72726524                          NaN
10149       2015-05-15   63191770                          NaN
10150       2016-05-12   73912140                          NaN
            2016-11-02   78499460                          NaN
            2017-04-19   83929378                          NaN
            2017-07-13   86270628                          NaN
                         86283522                          NaN
10151       2016-06-06   74581562                          NaN
            2016-09-15   77017352                          NaN
            2016-11-16   78978080                          NaN
            2017-05-30   84968400                          NaN
            2017-09-04   87364680                          NaN
            2017-09-05   87403348                            E
10157       2015-09-25   66731406                          NaN
            2016-08-08   76127670                            S
10158       2015-09-25   66731456                          NaN
10161       2016-06-23   75092972                          NaN
            2017-05-30   84966748                          NaN
10162       2016-11-07   78679328                          NaN
10173       2016-01-18   70431504                          NaN
            2016-03-01   71824972                          NaN
10182       2017-10-17   88747882                            B
10186       2016-02-29   71775132                          NaN
            2016-12-15   79963306                            B
            2017-01-16   80960260                          NaN
10188       2016-12-15   79959630                          NaN
10196       2016-09-15   77023356                          NaN
            2016-11-08   78728066                          NaN
10200       2016-12-19   80067172                          NaN
            2017-02-24   82241984                          NaN
            2017-04-27   84148728                          NaN
            2017-06-01   85044580                          NaN
            2017-07-08   86138630                          NaN
10202       2015-04-20   62531692                          NaN
            2015-04-23   62645658                          NaN
            2016-02-01   70916040                          NaN
            2016-07-25   75804950                          NaN
            2016-09-21   77204308                          NaN
10203       2016-12-23   80266514                            A
            2017-03-02   82408854                            A
            2017-04-03   83448848                          NaN
            2017-05-23   84812254                          NaN
            2017-09-13   87627698                          NaN
10218       2017-04-04   83463744                          NaN
                         83486896                          NaN
10223       2016-07-21   75765602                          NaN
            2017-07-10   86169274                          NaN

                                         ACTUAL_START_DATE ACTUAL_END_DATE  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10135       2017-09-04   87371802               2017-09-05      2017-09-05
            2017-09-11   87530552               2017-09-15      2017-09-15
10145       2016-03-01   71826460                      NaT             NaT
            2016-03-31   72726524               2016-05-02      2016-05-02
10149       2015-05-15   63191770               2015-06-18      2015-06-18
10150       2016-05-12   73912140               2016-06-15      2016-06-15
            2016-11-02   78499460               2016-11-03      2016-11-03
            2017-04-19   83929378               2017-05-22      2017-05-22
            2017-07-13   86270628               2017-07-13      2017-07-13
                         86283522               2017-07-15      2017-07-15
10151       2016-06-06   74581562               2016-07-12      2016-07-12
            2016-09-15   77017352               2016-10-10      2016-10-10
            2016-11-16   78978080               2016-12-16      2016-12-16
            2017-05-30   84968400               2017-06-30      2017-06-30
            2017-09-04   87364680               2017-09-04      2017-09-04
            2017-09-05   87403348                      NaT             NaT
10157       2015-09-25   66731406               2015-10-15      2015-10-15
            2016-08-08   76127670                      NaT             NaT
10158       2015-09-25   66731456               2015-10-15      2015-10-15
10161       2016-06-23   75092972               2016-08-19      2016-08-19
            2017-05-30   84966748               2017-06-15      2017-06-15
10162       2016-11-07   78679328               2016-11-24      2016-11-24
10173       2016-01-18   70431504               2016-01-19      2016-01-19
            2016-03-01   71824972               2016-03-01      2016-03-01
10182       2017-10-17   88747882                      NaT             NaT
10186       2016-02-29   71775132               2016-02-29      2016-02-29
            2016-12-15   79963306                      NaT             NaT
            2017-01-16   80960260               2017-02-08      2017-02-08
10188       2016-12-15   79959630               2017-01-26      2017-01-26
10196       2016-09-15   77023356               2016-10-06      2016-10-06
            2016-11-08   78728066               2016-11-09      2016-11-09
10200       2016-12-19   80067172               2017-01-16      2017-01-16
            2017-02-24   82241984               2017-02-25      2017-02-25
            2017-04-27   84148728               2017-04-28      2017-04-28
            2017-06-01   85044580               2017-06-01      2017-06-01
            2017-07-08   86138630               2017-07-12      2017-07-12
10202       2015-04-20   62531692               2015-04-21      2015-04-21
            2015-04-23   62645658               2015-04-27      2015-04-27
            2016-02-01   70916040               2016-02-02      2016-02-02
            2016-07-25   75804950               2016-07-25      2016-07-25
            2016-09-21   77204308               2016-09-22      2016-09-22
10203       2016-12-23   80266514                      NaT             NaT
            2017-03-02   82408854                      NaT             NaT
            2017-04-03   83448848               2017-05-04      2017-05-04
            2017-05-23   84812254               2017-05-26      2017-05-26
            2017-09-13   87627698               2017-09-19      2017-09-19
10218       2017-04-04   83463744               2017-04-04      2017-04-04
                         83486896               2017-04-04      2017-04-04
10223       2016-07-21   75765602               2016-09-01      2016-09-01
            2017-07-10   86169274               2017-09-12      2017-09-12

                                           INCIDENT_TYPE_NAME  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10135       2017-09-04   87371802                   Dépannage
            2017-09-11   87530552                   Dépannage
10145       2016-03-01   71826460                   Entretien
            2016-03-31   72726524                   Entretien
10149       2015-05-15   63191770                   Entretien
10150       2016-05-12   73912140                   Entretien
            2016-11-02   78499460                   Dépannage
            2017-04-19   83929378                   Entretien
            2017-07-13   86270628                   Dépannage
                         86283522                   Dépannage
10151       2016-06-06   74581562                   Dépannage
            2016-09-15   77017352                   Entretien
            2016-11-16   78978080                   Entretien
            2017-05-30   84968400                   Entretien
            2017-09-04   87364680                   Dépannage
            2017-09-05   87403348                   Dépannage
10157       2015-09-25   66731406                   Entretien
            2016-08-08   76127670                   Entretien
10158       2015-09-25   66731456                   Entretien
10161       2016-06-23   75092972                   Entretien
            2017-05-30   84966748                   Entretien
10162       2016-11-07   78679328                   Entretien
10173       2016-01-18   70431504         Dépannage+Entretien
            2016-03-01   71824972                   Dépannage
10182       2017-10-17   88747882                   Entretien
10186       2016-02-29   71775132                   Entretien
            2016-12-15   79963306                   Entretien
            2017-01-16   80960260                   Entretien
10188       2016-12-15   79959630                   Entretien
10196       2016-09-15   77023356                   Entretien
            2016-11-08   78728066                   Dépannage
10200       2016-12-19   80067172                   Entretien
            2017-02-24   82241984                   Dépannage
            2017-04-27   84148728                   Dépannage
            2017-06-01   85044580                   Dépannage
            2017-07-08   86138630                   Dépannage
10202       2015-04-20   62531692         Dépannage+Entretien
            2015-04-23   62645658                   Dépannage
            2016-02-01   70916040                   Entretien
            2016-07-25   75804950                   Dépannage
            2016-09-21   77204308                   Dépannage
10203       2016-12-23   80266514                   Entretien
            2017-03-02   82408854                   Entretien
            2017-04-03   83448848                   Entretien
            2017-05-23   84812254                   Dépannage
            2017-09-13   87627698                   Dépannage
10218       2017-04-04   83463744                   Dépannage
                         83486896                   Dépannage
10223       2016-07-21   75765602                   Entretien
            2017-07-10   86169274                   Entretien

                                         SCHEDULED_START_DATE  \
INSTANCE_ID CRE_DATE_GZL INCIDENT_NUMBER
10135       2017-09-04   87371802                  2017-09-05
            2017-09-11   87530552                  2017-09-15
10145       2016-03-01   71826460                  2016-04-05
            2016-03-31   72726524                  2016-05-02
10149       2015-05-15   63191770                  2015-06-18
10150       2016-05-12   73912140                  2016-06-15
            2016-11-02   78499460                  2016-11-03
            2017-04-19   83929378                  2017-05-22
            2017-07-13   86270628                  2017-07-13
                         86283522                  2017-07-15
10151       2016-06-06   74581562                  2016-07-12
            2016-09-15   77017352                  2016-10-10
            2016-11-16   78978080                  2016-12-16
            2017-05-30   84968400                  2017-06-30
            2017-09-04   87364680                  2017-09-04
            2017-09-05   87403348                  2017-09-08
10157       2015-09-25   66731406                  2015-10-15
            2016-08-08   76127670                  2016-09-28
10158       2015-09-25   66731456                  2015-10-15
10161       2016-06-23   75092972                  2016-08-19
            2017-05-30   84966748                  2017-06-15
10162       2016-11-07   78679328                  2016-11-24
10173       2016-01-18   70431504                  2016-01-19
            2016-03-01   71824972                  2016-03-01
10182       2017-10-17   88747882                  2017-11-08
10186       2016-02-29   71775132                  2016-02-29
            2016-12-15   79963306                  2017-01-18
            2017-01-16   80960260                  2017-02-08
10188       2016-12-15   79959630                  2017-01-26
10196       2016-09-15   77023356                  2016-10-06
            2016-11-08   78728066                  2016-11-09
10200       2016-12-19   80067172                  2017-01-16
            2017-02-24   82241984                  2017-02-25

Target test is not perfect but good enough for the moment.<br>
No need to spend more time on it as long as I am not sure I can use history (i.e. do other tables only have obs from training or the full data ?)

If improvment is needed: 
- delete last obs of each instance_id
- check for better handling of cancelled obs (mb take them out before computing time delta)

## Check if obs from other tables are in train / test / history
Yes, those tables are in train, test and history <br>
That means we can create features on them and use history to train on more datas

In [51]:
print(len(set(equipment.INSTANCE_ID) & set(intervention_train.INSTANCE_ID)))
print(len(set(equipment.INSTANCE_ID) & set(intervention_test.INSTANCE_ID)))
print(len(set(equipment.INSTANCE_ID) & set(intervention_history.INSTANCE_ID)))

462663
226770
795394

In [52]:
print(len(set(contract_history.INSTANCE_ID) & set(intervention_train.INSTANCE_ID)))
print(len(set(contract_history.INSTANCE_ID) & set(intervention_test.INSTANCE_ID)))
print(len(set(contract_history.INSTANCE_ID) & set(intervention_history.INSTANCE_ID)))

462663
221930
793033

In [54]:
print(len(set(intervention_train.INSTANCE_ID)))
print(len(set(intervention_test.INSTANCE_ID)))
print(len(set(intervention_history.INSTANCE_ID)))

462663
226770
795394

## merge everything

In [ ]:
# intervention
# equipment
# organization

### Equipment

In [55]:
equipment.head()

,INSTANCE_ID,LOCATION_ID,ORGANISATION_ID,PARTY_ID_OCC,TYPE_OCC,INSTALL_DATE,RACHAT_CODE,RACHAT_LIB,RACHAT_DATE,NATURE_CODE,...,TYPE_VOIE,VILLE,POINTS_FIDEL,STOP_PHONING,CODE_GEN_EQUIPEMENT,CODE_FONCTION,CODE_ENERGIE,CODE_INSTALLATION,CODE_SPECIFICATION,CODE_EAU_CHAUDE
0,1240047,8227277,1143,1644459,PROPRIETAIRE,2003-02-01,NaN,NaN,NaN,G-1-C-T-2,...,AV,SOLLIES PONT,1000.0,Y,G1,G,1.0,C,T,2
1,1240050,8227956,1143,1644453,PROPRIETAIRE,2007-06-01,NaN,NaN,NaN,G-1-C-I-1,...,AV,SOLLIES PONT,1000.0,NaN,G1,G,1.0,C,I,1
2,1240051,8234246,1143,1644840,PROPRIETAIRE,2001-06-01,NaN,NaN,NaN,G-1-C-I-3,...,TRA,TOULON,1000.0,NaN,G1,G,1.0,C,I,3
3,1240275,8235019,1143,1652047,PROPRIETAIRE,2003-11-01,NaN,NaN,NaN,G-1-C-H-1,...,RUE,LA SEYNE SUR MER,1000.0,NaN,G1,G,1.0,C,H,1
4,1240277,8234808,1143,1651224,PROPRIETAIRE,1996-07-01,NaN,NaN,NaN,G-1-C-H-1,...,BD,LA SEYNE SUR MER,1000.0,NaN,G1,G,1.0,C,H,1

In [56]:
equipment.columns

Index(['INSTANCE_ID', 'LOCATION_ID', 'ORGANISATION_ID', 'PARTY_ID_OCC',
       'TYPE_OCC', 'INSTALL_DATE', 'RACHAT_CODE', 'RACHAT_LIB', 'RACHAT_DATE',
       'NATURE_CODE', 'MARQUE_CODE', 'MARQUE_LIB', 'MODELE_CODE', 'MODELE_LIB',
       'USAGE_LOCAL', 'LOCALISATION_ORGANISME', 'COMPLEMENT_RUE',
       'CODE_POSTAL', 'ESCALIER', 'ETAGE', 'NUMERO', 'RUE', 'PAYS',
       'TYPE_VOIE', 'VILLE', 'POINTS_FIDEL', 'STOP_PHONING',
       'CODE_GEN_EQUIPEMENT', 'CODE_FONCTION', 'CODE_ENERGIE',
       'CODE_INSTALLATION', 'CODE_SPECIFICATION', 'CODE_EAU_CHAUDE'],
      dtype='object')

In [58]:
useless_variables = ['CODE_POSTAL', 'ETAGE', 'PAYS', 'POINTS_FIDEL', 'STOP_PHONING']
equipment.drop(useless_variables, axis=1, inplace=True)

### Contract
Some aggregation should be used in feature ingineering

In [85]:
useless_variables = [ 'CONTRACT_NUMBER', 'CONTRACT_MODIFICATEUR', 'CRE_DATE', 
       'CONDITION_REGLEMENT', 'MOTIF_RESILIATION', 'RENOUVELLEMENT_AGENCE',
       'PRIX_FORMULE', 'PRIX_OPTION', 'NUM_CAMPAGNE', 'DATE_RESILIATION']
contract_history.drop(useless_variables, axis=1, inplace=True)

In [74]:
contract_history.head(50)

,STS_CODE,UPD_DATE,DATE_RESILIATION,DATE_DEBUT,DATE_FIN,INSTANCE_ID,FORMULE,OPTION,CONTRAT_TARIF,PRIX_FACTURE
0,TERMINATED,2015-10-12 12:26:24,2015-04-10 00:00:00,2015-04-10 00:00:00,2016-04-09 00:00:00,15447048,SECURITE*,NaN,77,77
1,TERMINATED,2015-03-19 04:12:36,2015-03-19 00:00:00,2015-03-19 00:00:00,2016-03-18 00:00:00,13172466,SECURITE*,NaN,164,253
2,EXPIRED,2016-01-01 02:43:12,NaN,2015-01-01 00:00:00,2015-12-31 00:00:00,37101538,SECURITE*,NaN,162,0
3,TERMINATED,2015-03-21 04:17:27,2015-03-20 00:00:00,2015-03-24 00:00:00,2016-03-23 00:00:00,2028002,INTEGRAL***,NaN,242,259
4,ACTIVE_KI,2015-05-10 00:16:44,NaN,2015-03-24 00:00:00,2016-03-23 00:00:00,8774167,INTEGRAL***,NaN,242,242
5,EXPIRED,2016-03-24 00:33:26,NaN,2015-03-24 00:00:00,2016-03-23 00:00:00,8774167,INTEGRAL***,NaN,242,242
6,TERMINATED,2015-03-01 05:24:54,2015-03-01 00:00:00,2015-03-01 00:00:00,2016-02-29 00:00:00,2923109,SECURITE*,RAMONAGE FIOUL,252,195
7,ACTIVE_KI,2015-09-08 04:08:18,NaN,2015-09-08 00:00:00,2016-09-07 00:00:00,37253750,SECURITE*,NaN,142,0
8,EXPIRED,2016-09-08 01:39:00,NaN,2015-09-08 00:00:00,2016-09-07 00:00:00,37253750,SECURITE*,NaN,142,0
9,TERMINATED,2015-03-29 03:07:21,2015-03-29 00:00:00,2015-03-29 00:00:00,2016-03-28 00:00:00,1933995,SECURITE*,NaN,164,204
10,TERMINATED,2015-03-01 05:24:54,2015-03-01 00:00:00,2015-03-01 00:00:00,2016-02-29 00:00:00,73751,SECURITE*,NaN,164,164
11,TERMINATED,2015-12-23 22:07:46,2015-12-23 00:00:00,2015-04-11 00:00:00,2016-04-10 00:00:00,1706992,SECURITE*,NaN,142,130
12,TERMINATED,2015-10-06 11:41:45,2015-10-06 00:00:00,2015-04-01 00:00:00,2016-03-31 00:00:00,515890,SECURITE*,NaN,81,81
13,TERMINATED,2015-11-03 09:22:36,2015-04-02 00:00:00,2015-04-02 00:00:00,2016-04-01 00:00:00,2130603,SECURITE*,NaN,142,136
14,TERMINATED,2015-06-18 12:43:29,2015-04-07 00:00:00,2015-04-07 00:00:00,2016-04-06 00:00:00,35104874,SECURITE*,NaN,243,243
15,TERMINATED,2015-06-18 00:44:39,2015-06-16 00:00:00,2015-04-07 00:00:00,2016-04-06 00:00:00,35111999,SECURITE*,NaN,142,142
16,TERMINATED,2015-04-11 05:05:14,2015-04-11 00:00:00,2015-04-11 00:00:00,2016-04-10 00:00:00,35123747,SECURITE*,NaN,81,81
17,TERMINATED,2015-08-10 14:07:00,2015-07-23 00:00:00,2015-03-26 00:00:00,2016-03-25 00:00:00,33567460,SECURITE*,NaN,142,142
18,TERMINATED,2015-03-02 00:00:31,2015-03-02 00:00:00,2015-03-02 00:00:00,2016-03-01 00:00:00,129689,SECURITE*,RAMONAGE FIOUL,220,242
19,ACTIVE_KI,2015-04-11 05:07:41,NaN,2015-04-11 00:00:00,2016-04-10 00:00:00,35121762,SECURITE*,NaN,142,142
20,EXPIRED,2016-04-11 00:16:08,NaN,2015-04-11 00:00:00,2016-04-10 00:00:00,35121762,SECURITE*,NaN,142,142
21,EXPIRED,2016-01-09 08:55:31,NaN,2015-01-09 00:00:00,2016-01-08 00:00:00,37253985,SECURITE*,NaN,142,0
22,TERMINATED,2015-06-13 05:23:09,2015-06-12 00:00:00,2015-04-10 00:00:00,2016-04-09 00:00:00,35121765,SECURITE*,NaN,142,135
23,TERMINATED,2015-03-20 01:37:45,2015-03-01 00:00:00,2015-03-01 00:00:00,2016-02-29 00:00:00,33450998,INTEGRAL***,NaN,242,251
24,TERMINATED,2015-11-24 09:02:35,2015-03-04 00:00:00,2015-03-04 00:00:00,2016-03-03 00:00:00,35024121,SECURITE*,NaN,182,189
25,TERMINATED,2015-04-10 07:07:43,2015-04-09 00:00:00,2015-04-09 00:00:00,2016-04-08 00:00:00,23070639,SECURITE*,NaN,150,247
26,TERMINATED,2015-04-10 07:07:43,2015-04-09 00:00:00,2015-04-09 00:00:00,2016-04-08 00:00:00,35061912,SECURITE*,NaN,247,196
27,ACTIVE_KI,2015-06-27 03:29:52,NaN,2015-06-27 00:00:00,2016-06-26 00:00:00,37253811,INTEGRAL***,NaN,242,0
28,EXPIRED,2016-06-27 00:01:01,NaN,2015-06-27 00:00:00,2016-06-26 00:00:00,37253811,INTEGRAL***,NaN,242,0
29,TERMINATED,2015-04-04 10:49:17,2015-04-04 00:00:00,2015-04-04 00:00:00,2016-04-03 00:00:00,2160244,SECURITE*,NaN,142,142
30,TERMINATED,2015-07-28 08:56:02,2015-03-16 00:00:00,2015-03-16 00:00:00,2016-03-15 00:00:00,24739799,SECURITE*,NaN,243,485
31,TERMINATED,2015-03-05 04:39:04,2015-03-04 00:00:00,2015-03-04 00:00:00,2016-03-03 00:00:00,17183887,SECURITE*,Gicleur fioul / RAMONAGE FIOUL,275,275
32,TERMINATED,2015-08-03 01:55:45,2015-04-05 00:00:00,2015-04-05 00:00:00,2016-04-04 00:00:00,35095698,SECURITE*,NaN,142,142
33,ACTIVE_KI,2015-03-12 04:07:09,NaN,2015-03-12 00:00:00,2016-03-11 00:00:00,24330086,SECURITE*,NaN,142,153
34,ACTIVE_KI,2015-04-19 10:34:53,NaN,2015-04-09 00:00:00,2016-04-08 00:00:00,35105241,SECURITE*,RAMONAGE FIOUL,220,214
35,ACTIVE_KI,2015-03-11 03:44:07,NaN,2015-03-11 00:00:00,2016-03-10 00:00:00,929680,SECURITE*,NaN,142,142
36,EXPIRED,2016-03-11 03:28:10,NaN,2015-03-11 00:00:00,2016-03-10 00:00:00,929680,SECURITE*,NaN,142,142
37,EXPIRED,2016-01-02 00:47:52,NaN,2015-01-02 00:00:00,2016-01-01 00:00:00,36902750,SECURITE*,NaN,142,142
38,ACTIVE_KI,2016-02-18 11:04:36,2016-02-18 00:00:00,2015-03-31 00:00:00,2016-03-30 00:00:00,6028481,SECURITE*,NaN,142,141
39,TERMINATED,2016-02-19 02:43:55,2016-02-18 00:00:00,2015-03-31 00:00:00,2016-03-30 00:00:00,6028481,SECURITE*,NaN,142,141
40,TERMINATED,2015-08-27 10:40:45,2015-08-19 00:00:00,2015-03-17 00:00:00,2016-03-16 00:00:00,2410647,SECURITE*,NaN,142,141
41,ACTIVE_KI,2015-04-03 09:03:34,NaN,2015-04-03 00:00:00,2016-04-02 00:00:00,2272725,SECURITE*,NaN,142,120
42,EXPIRED,2016-04-03 00:51:37,NaN,2015-04-03 00:00:00,2016-04-02 00:00:00,2272725,SECURITE*,NaN,142,120
43,ACTIVE_KI,2016-02-19 11:18:56,2016-03-01 00:00:00,2015-04-09 00:00:00,2016-04-08 00:00:00,35086855,ESSENTIEL P2,NaN,106,106
44,TERMINATED,2016-03-01 02:41:22,2016-03-01 00:00:00,2015-04-09 00:00:00,2016-04-08 00:00:00,35086855,ESSENTIEL P2,NaN,106,106
45,TERMINATED,2015-04-08 05:33:41,2015-04-08 00:00:00,2015-04-08 00:00:00,2016-04-07 00:00:00,12534733,SECURITE*,NaN,142,142
46,TERMINATED,2015-03-17 04:57:25,2015-03-17 00:00:00,2015-03-17 00:00:00,2016-03-16 00:00:00,835039,SECURITE*,NaN,164,139
47,TERMINATED,2015-03-05 04:40:06,2015-03-05 00:00:00,2015-03-05 00:00:00,2016-03-04 00:00:00,7027886,SECURITE*,NaN,162,162
48,TERMINATED,2015-03-06 04:16:08,2015-03-06 00:00:00,2015-03-06 00:00:00,2016-03-05 00:00:00,1771901,SECURITE*,NaN,142,170
49,TERMINATED,2015-03-25 04:15:18,2015-03-25 00:00:00,2015-03-25 00:00:00,2016-03-24 00:00:00,33572137,INTEGRAL***,7/7,289,255

In [88]:
contract_history.isnull().sum()

STS_CODE         0
UPD_DATE         0
DATE_DEBUT       0
DATE_FIN         0
INSTANCE_ID      0
FORMULE          0
OPTION           0
CONTRAT_TARIF    0
PRIX_FACTURE     0
dtype: int64

In [87]:
contract_history.OPTION.fillna("NO", inplace=True)

In [89]:
contract_history.STS_CODE.value_counts()

ACTIVE_KI          1640274
FUTUR_RENOUVELE    1311850
EXPIRED             874995
TERMINATED          652049
PROPOSED            148072
SIGNED               52239
FUTUR                41413
QA_HOLD                109
HOLD                    95
Name: STS_CODE, dtype: int64

In [90]:
# find appropriate contract at the moment of the call
groups = contract_history[['INSTANCE_ID', 'UPD_DATE']].merge(intervention_train[['INSTANCE_ID', 'CRE_DATE_GZL']])

In [92]:
groups = groups.loc[groups.UPD_DATE <=  groups.CRE_DATE_GZL, :].groupby(['INSTANCE_ID', 'CRE_DATE_GZL'])

In [95]:
update_date = groups.max()

In [100]:
intervention_train = intervention_train.merge(update_date, left_on=['INSTANCE_ID', 'CRE_DATE_GZL'], right_index=True)

In [ ]:
intervention_train = intervention_train.merge(contract_history, on='UPD_DATE')

In [ ]:
# feature ingeneering:
# dates: compute timedelta between update_date and creation_date
# computation timedelta between creation_date and creation_date

### Organisation

Probably useless ...

In [65]:
organisation.columns

Index(['L1_ORGANISATION_ID', 'L1_NAME', 'L2_ORGANISATION_ID', 'L2_NAME',
       'ADRESSE', 'L2_ORGA_CODE_POSTAL', 'L2_ORGA_VILLE', 'CIA',
       'ORGANISATION_CODE'],
      dtype='object')

In [ ]:
useless_variables = ['L1_ORGANISATION_ID', 'L2_ORGANISATION_ID', 'CIA']
equipment.drop(useless_variables, axis=1, inplace=True)

## merge

In [ ]:
def prepare_data(data_):
    data = data_.merge(equipement_df, how='left', on='INSTANCE_ID').merge(orga_df, how='left', left_on='ORGANISATION_ID', right_on='L2_ORGANISATION_ID')
    contrat_history_s = data[['INCIDENT_NUMBER', 'INSTANCE_ID','CRE_DATE_GZL']].merge(contrat_history_df).query('CRE_DATE_GZL>=UPD_DATE_date')
    contrat_history_s = contrat_history_s.sort_values(['INCIDENT_NUMBER', 'UPD_DATE'], ascending=[True,False]).drop_duplicates(keep='first', subset=['INCIDENT_NUMBER'])
    data = data.merge(contrat_history_s, how='left').merge(nature_code_eau_chaude, how='left')
    data = data.merge(nature_code_energie, how='left').merge(nature_code_fonction, how='left')
    data = data.merge(nature_code_installation, how='left').merge(nature_code_specification, how='left')
    print(data.shape[0], data.INCIDENT_NUMBER.nunique(), data.INSTANCE_ID.nunique())
    return data

In [ ]:
drop_columns = ['CRE_DATE_date', 'UPD_DATE_date']

In [ ]:
train_data = prepare_data(intervention_train_df).drop(drop_columns, axis=1)

In [ ]:
test_data = prepare_data(intervention_test_df).drop(drop_columns, axis=1)

In [ ]:
history_data = prepare_data(intervention_history_df).drop(drop_columns, axis=1)

## Check unclear variables

In [66]:
intervention_train.columns

Index(['INSTANCE_ID', 'CRE_DATE_GZL', 'INCIDENT_NUMBER', 'index',
       'INCIDENT_TYPE_ID', 'INCIDENT_TYPE_NAME', 'TYPE_BI', 'NB_PASSAGE',
       'MILLESIME', 'PROBLEM_CODE', 'PROBLEM_DESC', 'AUTEUR_INCIDENT',
       'ORIGINE_INCIDENT', 'COMMENTAIRE_BI', 'SS_TR_FLAG', 'TYPE_UT',
       'GRAVITE', 'RESOURCE_ID', 'SCHEDULED_START_DATE', 'SCHEDULED_END_DATE',
       'target'],
      dtype='object')

## Univariate analysis

In [ ]:
df.target.value_counts()

In [ ]:
sns.countplot(x="deck", data=titanic, palette="Greens_d");

## Bivariate analysis

In [ ]:
sns.pairplot(intervention_train, hue='target')

In [ ]:
sns.barplot(x="MILLESIME", y="target", data=df)

In [ ]:
sns.barplot(x="MILLESIME", y="target", hue="PROBLEM_CODE", data=df)

In [ ]:
#type BI et type UT are the same
pd.crosstab(train.TYPE_BI, train.TYPE_UT)

In [ ]:
#CIA, ORGANISATION_CODE and L2_organization_id are the same
pd.crosstab(train.CIA, train.L2_ORGANISATION_ID)

## first model

In [ ]:
# preprocessing for categorical variables and dates

In [ ]:
# svm

## build output file